// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/lukaproject/schedulersvr/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/addTask",
				Handler: AddTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/getTask",
				Handler: GetTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/worker/fetchTask",
				Handler: FetchTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/worker/updateTask",
				Handler: UpdateTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/worker/addWorker",
				Handler: AddWorkerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/removeWorkerByName",
				Handler: RemoveWorkerByNameHandler(serverCtx),
			},
		},
	)
}
